### ISSUE TITLE
Question About Replacing SemanticKITTI Dataset with Custom Dataset

### ISSUE THREAD

**Issue by xiaosa269** [Xiangxu-0103/FRNet#27]
Hello, thank you very much for your work.
I tried to replace the semanticKITTI dataset with my own dataset, but I encountered the following error during training. I have tried many methods, but I still couldn't solve this issue. Do you know how to fix it? Thank you very much for your help.

**05/31 20:22:55 - mmengine - INFO - Iter(train) [  950/50000]  lr: 6.1179e-04  eta: 20:29:54  time: 1.5111  data_time: 0.0034  memory: 5897  loss: 5.7215  decode.loss_ce: 0.1238  aux_0.loss_ce: 0.0053  aux_0.loss_lovasz: 0.4535  aux_0.loss_boundary: 0.8194  aux_1.loss_ce: 0.0063  aux_1.loss_lovasz: 0.4696  aux_1.loss_boundary: 0.8386  aux_2.loss_ce: 0.0077  aux_2.loss_lovasz: 0.5261  aux_2.loss_boundary: 0.8952  aux_3.loss_ce: 0.0099  aux_3.loss_lovasz: 0.6142  aux_3.loss_boundary: 0.9518
05/31 20:24:10 - mmengine - INFO - Exp name: frnet-2024_20240531_195901
05/31 20:24:10 - mmengine - INFO - Iter(train) [ 1000/50000]  lr: 6.3451e-04  eta: 20:28:07  time: 1.4915  data_time: 0.0033  memory: 6054  loss: 5.6490  decode.loss_ce: 0.1204  aux_0.loss_ce: 0.0046  aux_0.loss_lovasz: 0.4391  aux_0.loss_boundary: 0.8167  aux_1.loss_ce: 0.0058  aux_1.loss_lovasz: 0.4600  aux_1.loss_boundary: 0.8354  aux_2.loss_ce: 0.0078  aux_2.loss_lovasz: 0.5091  aux_2.loss_boundary: 0.8953  aux_3.loss_ce: 0.0102  aux_3.loss_lovasz: 0.5944  aux_3.loss_boundary: 0.9502
/home/xhy/code/FRNet-master1/frnet/datasets/transforms/transforms_3d.py:188: RuntimeWarning: invalid value encountered in divide
  pitch = np.arcsin(points_numpy[:, 2] / depth)
/home/xhy/code/FRNet-master1/frnet/datasets/transforms/transforms_3d.py:205: RuntimeWarning: invalid value encountered in cast
  proj_y = np.maximum(0, proj_y).astype(np.int64)
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 129, in main
    runner.train()
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/mmengine/runner/loops.py", line 284, in run
    self.runner.val_loop.run()
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/mmengine/runner/loops.py", line 362, in run
    for idx, data_batch in enumerate(self.dataloader):
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 403, in __getitem__
    data = self.prepare_data(idx)
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/mmdet3d/datasets/seg3d_dataset.py", line 305, in prepare_data
    return super().prepare_data(idx)
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 793, in prepare_data
    return self.pipeline(data_info)
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 60, in __call__
    data = t(data)
  File "/home/xhy/miniconda3/envs/frnet1/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/xhy/code/FRNet-master1/frnet/datasets/transforms/transforms_3d.py", line 210, in transform
    proj_idx[proj_y[order], proj_x[order]] = indices[order]
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 64**

**Comment by Xiangxu-0103** [comment]
Hi @xiaosa269 , are you willing to share more information about the modification and dataset? From the info above, I cannot locate the issue.
